//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PromadEntities : DbContext
    {
        public PromadEntities()
            : base("name=PromadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proovedores> Proovedores { get; set; }
    
        public virtual int ProductosAdd(Nullable<int> idProovedor, string codigo, string descripcion, string unidad, Nullable<decimal> costo)
        {
            var idProovedorParameter = idProovedor.HasValue ?
                new ObjectParameter("IdProovedor", idProovedor) :
                new ObjectParameter("IdProovedor", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("Unidad", unidad) :
                new ObjectParameter("Unidad", typeof(string));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("Costo", costo) :
                new ObjectParameter("Costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductosAdd", idProovedorParameter, codigoParameter, descripcionParameter, unidadParameter, costoParameter);
        }
    
        public virtual ObjectResult<ProductosGetAll_Result> ProductosGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductosGetAll_Result>("ProductosGetAll");
        }
    
        public virtual int ProovedoresAdd(string codigo, string razonSocial, string rFC)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var razonSocialParameter = razonSocial != null ?
                new ObjectParameter("RazonSocial", razonSocial) :
                new ObjectParameter("RazonSocial", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProovedoresAdd", codigoParameter, razonSocialParameter, rFCParameter);
        }
    
        public virtual int ProovedoresDelete(Nullable<int> idProovedor)
        {
            var idProovedorParameter = idProovedor.HasValue ?
                new ObjectParameter("IdProovedor", idProovedor) :
                new ObjectParameter("IdProovedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProovedoresDelete", idProovedorParameter);
        }
    
        public virtual ObjectResult<ProovedoresGetById_Result> ProovedoresGetById(Nullable<int> idProovedor)
        {
            var idProovedorParameter = idProovedor.HasValue ?
                new ObjectParameter("IdProovedor", idProovedor) :
                new ObjectParameter("IdProovedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProovedoresGetById_Result>("ProovedoresGetById", idProovedorParameter);
        }
    
        public virtual int ProovedoresUpdate(Nullable<int> idProovedor, string codigo, string razonSocial, string rFC)
        {
            var idProovedorParameter = idProovedor.HasValue ?
                new ObjectParameter("IdProovedor", idProovedor) :
                new ObjectParameter("IdProovedor", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var razonSocialParameter = razonSocial != null ?
                new ObjectParameter("RazonSocial", razonSocial) :
                new ObjectParameter("RazonSocial", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProovedoresUpdate", idProovedorParameter, codigoParameter, razonSocialParameter, rFCParameter);
        }
    
        public virtual ObjectResult<ProductosGetDeleteId_Result> ProductosGetDeleteId(Nullable<int> idProovedor)
        {
            var idProovedorParameter = idProovedor.HasValue ?
                new ObjectParameter("IdProovedor", idProovedor) :
                new ObjectParameter("IdProovedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductosGetDeleteId_Result>("ProductosGetDeleteId", idProovedorParameter);
        }
    
        public virtual ObjectResult<ProovedoresGetAll_Result> ProovedoresGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProovedoresGetAll_Result>("ProovedoresGetAll");
        }
    }
}
